apiVersion: apps/v1
kind: Deployment
metadata:
  name: pragati-deploy
  labels:
    app: pragati-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pragati-app
  template:
    metadata:
      labels:
        app: pragati-app
    spec:
      containers:
      - name: loksai-eta-container
        image: pragatipatil1425/sa-wd-webapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pragati-np-service
  labels:
    app: pragati-app
spec:
  selector:
    app: pragati-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
